### ISSUE TITLE
Standalone 1.17

### ISSUE THREAD

**Issue by DamnUi** [19MisterX98/DiamondSim#10]
Hey, I am sorry i'm asking this off you i am probably wasting your time but i know absolutely nothing about java.
You must have heard that Atomic has been made private, and wont be updated anymore the GUI itself has many issues so id really appreciate if you cloud extract the oresim module from it and make it a standalone. 
Again i apologize if this task wastes your time but i'm sure a lot of people would appreciate it.

Thank you very much!
ps: Your work on seed crackerx was amazing keep it up! :)

**Comment by HatingMyself** [comment]
Yes, please release OreSim as a Standalone mod, since 0x150 tokenlogged Atomic, its not a trusted source anymore.

**Comment by DamnUi** [comment]
I dont think its token logged personally, and currently i have the file for it and its much better now and useable with wurst try it, it might work

**Comment by T14D3** [comment]
The problem with Atomic is that the oresim only works for a single Dimension, and is therefor 100% Useless for any server running Multiworld

**Comment by DamnUi** [comment]
I see, that’s sucks I’m sorry to have to trouble you with this
