### ISSUE TITLE
1.17?

### ISSUE THREAD

**Issue by DennisGHOSTDOGE** [19MisterX98/DiamondSim#3]
Yo, so I, a german as well, am very interested in this project. I looked at the code and tried to figure out how it worked, which was quite hard since I basically only know python, just to find out how I could update it to 1.17 or how I could add custom ores myself. Well, if you have time to tell me how it works, feel free to add me on discord, that would be dennis#3203

**Comment by Tiebe** [comment]
Updating this to 1.17 would probably require a rewrite of the entire mod, since the ore generation completely changes.

**Comment by 19MisterX98** [comment]
#7
