### ISSUE TITLE
Custom Ore

### ISSUE THREAD

**Issue by SpRoXx** [19MisterX98/DiamondSim#5]
This mod is really useful, That will be way more better if you can let us choose which ore to display

**Comment by ertugrulcakici** [comment]
I'm looking for the same thing. It would be perfect

**Comment by 19MisterX98** [comment]
A version with more ores is available in cornos https://github.com/cornos/Cornos

**Comment by ertugrulcakici** [comment]
Really ? Thanks a lot sir. How can i use it ? There are both x-ray and Oresim. I thought I'll use oresim for x-ray protected server but I  couldn't see set seed settings anywhere and it didn't explain anywhere as I saw.

**Comment by ertugrulcakici** [comment]
And is it Safe? in their discord channel i saw some claim which is says it a rat

**Comment by 19MisterX98** [comment]
Left click on oresim in the clickgui to see settings. Set the seed in chat with .setseed
If you feel insecure with the jar file you can build the mod from source code

**Comment by 19MisterX98** [comment]
Oh, 0x150 already helped you in cornos dc

**Comment by ertugrulcakici** [comment]
yes, he helped me. I'll try to build after install java again. Thanks both of you

**Comment by tester248** [comment]
I might be asking too much but if we can get diamondsim working with baritone mod that would be lit

**Comment by 19MisterX98** [comment]
> 
> 
> I might be asking too much but if we can get diamondsim working with baritone mod that would be lit

Maybe I'll do that in Atomic when baritone 1.17 drops
https://github.com/cornos/Atomic
